[package]
name = "code"
version = "0.1.0"
authors = ["Bryan Klimt <bklimt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vector2d = "2.2.0"
num-rational = "0.2"
