[package]
name = "monkeys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.25", features = ["derive"] }
thiserror = "1.0.37"
itertools = "0.10.5"
anyhow = "1.0"
